# Generated by Django 4.2 on 2023-05-03 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Copy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_avaliable", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="LoandBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("devoluiton_date", models.DateField()),
                ("borrowed_date", models.DateField(auto_now_add=True)),
                (
                    "copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copy_loand_book",
                        to="copies.copy",
                    ),
                ),
            ],
        ),
    ]
