# Generated by Django 4.2 on 2023-05-05 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Copy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_available", models.BooleanField(default=False)),
                (
                    "books",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copy_book",
                        to="books.book",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoandBook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "devolution_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                ("borrowed_date", models.DateField(auto_now_add=True)),
                (
                    "copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copy_loand_book",
                        to="copies.copy",
                    ),
                ),
                (
                    "users",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_loand_book",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="copy",
            name="user",
            field=models.ManyToManyField(
                related_name="book_loand",
                through="copies.LoandBook",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
