# Generated by Django 4.2 on 2023-05-03 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0001_initial"),
        ("copies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loandbook",
            name="users",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_loand_book",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="copy",
            name="books",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copy_book",
                to="books.book",
            ),
        ),
        migrations.AddField(
            model_name="copy",
            name="user",
            field=models.ManyToManyField(
                related_name="book_loand",
                through="copies.LoandBook",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
