# Generated by Django 4.2 on 2023-05-04 18:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="copy",
            old_name="is_avaliable",
            new_name="is_available",
        ),
    ]
