# Generated by Django 4.2 on 2023-05-02 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("copies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="copy",
            name="books",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copy_book",
                to="books.book",
            ),
        ),
        migrations.CreateModel(
            name="LoandBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("devoluiton_date", models.DateField()),
                ("borrowed_date", models.DateField(auto_now_add=True)),
                (
                    "copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copy_loand_book",
                        to="copies.copy",
                    ),
                ),
                (
                    "users",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_loand_book",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="copy",
            name="user",
            field=models.ManyToManyField(
                related_name="book_loand",
                through="copies.LoandBook",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
