# Generated by Django 4.2 on 2023-05-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0002_rename_is_avaliable_copy_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loandbook",
            name="devolution_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
