# Generated by Django 4.2 on 2023-05-03 23:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loandbook",
            old_name="devoluiton_date",
            new_name="devolution_date",
        ),
    ]
